General:
    comment:
    seed: 12321
    fp16: False
    precision: 32
    multi_gpu_mode: dp
    gpus: [0]
    epochs: &epoch 100
    grad_acc: 2
    frozen_bn: False
    patience: 50
    server: test
    log_path: logs/
Data:
    dataset_name: image_data
    data_shuffle: False
    data_dir: challenge5/data
    train_dataloader:
        batch_size: 64
        num_workers: 8
    test_dataloader:
        batch_size: 64
        num_workers: 8
Model:
    name: SIM_CLR
    n_classes: 3
Optimizer:
    opt: adamw
    lr: 0.00001
    opt_eps: null
    opt_betas: null
    momentum: null
    weight_decay: 0.001
Loss:
    base_loss: multi_view_xent


